// The M1 track, hand-authored (M1 road-1): Keys-flavoured coastal highway, only inspired by the
// Overseas Highway (the real one is the GIS side quest's). One main road through Catmull-Rom
// control points, cut into roads. Road-2 adds one junction pair: the boat-ramp cut splits off
// after the Marina Run, jumps a ramp and rejoins at the Pelican Channel Bridge, about 50 m shorter
// than the S-bends it skips. Road-3 (M2) carries the road on past the Sandbar Causeway, about
// 7.4 km more, so one network hosts three race lengths: short (the M1 sprint, about 3.5 km),
// standard (about 7.2 km, to the end of Conch Row) and long (about 11 km, over the long bridge to
// the Last Resort Causeway). The Keys are nearly flat, so the hills are exaggerated bridge humps.
// Every name and joke is a placeholder the maintainer may veto. Bake with
// `node tools/road/bake.mjs`.
//
// Frame: metres, x east, z south (north is -z). The start faces north.
import type { TrackSource } from '../../../src/road/compile';

// Travel lanes 4.0 m wide (M1 had 3.4 m): playtest 1 found the road too narrow to weave round
// traffic. The rideable shoulders stay 1.5 m, so the road's edge is 5.5 m either side of centre.
const LANES = [
  { id: 'L0', dCenterM: -4.75, widthM: 1.5, direction: -1, kind: 'shoulder' },
  { id: 'L1', dCenterM: -2, widthM: 4, direction: -1, kind: 'drive' },
  { id: 'R1', dCenterM: 2, widthM: 4, direction: 1, kind: 'drive' },
  { id: 'R0', dCenterM: 4.75, widthM: 1.5, direction: 1, kind: 'shoulder' },
] as const;

export const KEYS_M1: TrackSource = {
  network: {
    id: 'keys-m1',
    name: 'Keys M1 coastal highway (hand-authored)',
    region: 'florida-keys',
    crs: { kind: 'tmerc', originLatDeg: 24.7, originLonDeg: -81.1, originElevM: 0 },
    notes:
      'The hand-made Keys track: one main road, and the boat-ramp cut that splits off it at the marina and rejoins at the bridge. The split and merge junctions own connector roads; the other joins pass straight through. Three routes share it, one per race length (road-3).',
  },
  createdAt: '2026-09-30',
  points: [
    // The marina S-bends swing west (left) first, so the boat-ramp cut runs straight up their
    // east side. Everything after them is the road-1 shape, moved 220 m west.
    [0, 0],
    [0, -220],
    [-40, -410],
    [-150, -570],
    [-190, -760],
    [-110, -960],
    [-110, -1200],
    [-60, -1430],
    [60, -1630],
    [220, -1780],
    [420, -1880],
    [640, -1920],
    [840, -1930],
    [1020, -2010],
    [1110, -2190],
    [1100, -2400],
    [1030, -2600],
    [1030, -2800],
    // road-3: on north through the mangroves, then east along the flats, through town, over the
    // long bridge and out along the last causeway.
    [1060, -3000],
    [1150, -3180],
    [1150, -3380],
    [1060, -3560],
    [1080, -3760],
    [1200, -3920],
    [1380, -4010],
    [1600, -4040],
    [1820, -4000],
    [2040, -4060],
    [2240, -4180],
    [2380, -4350],
    [2560, -4460],
    [2780, -4500],
    [3000, -4480],
    [3240, -4520],
    [3700, -4600],
    [4200, -4640],
    [4700, -4620],
    [5200, -4560],
    [5550, -4560],
    [5850, -4640],
    [6100, -4800],
    [6300, -4980],
    [6600, -5080],
    [6900, -5060],
    [7250, -5000],
  ],
  baseElevationM: 1.5,
  spacingM: 2,
  smoothingM: 60,
  lanes: LANES,
  roads: [
    {
      id: 'm1-marina-run',
      name: 'Marina Run',
      lengthM: 300,
      speedLimitMps: 24.6,
      surface: 'asphalt',
      humps: [],
      // Run W-Q, distinct keys (interview, 2026-10-02): the start is Chum Key, the fishing village
      // (district tag `key-fishing`: shrimp boats on blocks, fish houses, buoy lines, trap stacks).
      tags: [
        { s0: 0, s1: 'end', side: 'right', tag: 'marina' },
        { s0: 0, s1: 'end', side: 'left', tag: 'strip-mall' },
        { s0: 0, s1: 'end', side: 'both', tag: 'key-fishing' },
      ],
      features: [
        {
          kind: 'billboard',
          id: 'sign-marina-chum-key',
          s0: 100,
          s1: 110,
          d0: 6.5,
          d1: 9,
          item: 'chum-key',
        },
        {
          kind: 'billboard',
          id: 'sign-marina-charters',
          s0: 60,
          s1: 70,
          d0: -9,
          d1: -6.5,
          item: 'charters-daily',
        },
        // Run W-P: the M1 signs that had no slot of their own until now.
        {
          kind: 'billboard',
          id: 'sign-marina-next-regret',
          s0: 240,
          s1: 250,
          d0: -9,
          d1: -6.5,
          item: 'next-regret',
        },
        { kind: 'copSpawn', id: 'bait-shop-lot', s0: 4, s1: 20, d0: 6.1, d1: 9.6 },
        // The junction choice, signed (W-R; interview, 2026-10-02: "junction choices in races"): the
        // boat-ramp cut's split is the last 40 m of the run, on the right.
        {
          kind: 'billboard',
          id: 'sign-marina-ramp-ahead',
          s0: 200,
          s1: 210,
          d0: 6.5,
          d1: 9,
          item: 'ramp-keep-right',
        },
        // road-3: a billboard in view from the start grid, across from the strip mall's lot.
        {
          kind: 'billboard',
          id: 'bb-marina-timeshare',
          s0: 150,
          s1: 190,
          d0: -16,
          d1: -7,
          item: 'timeshare',
        },
        // Playtest 1b quick wins: a boost pad on the right of the lane, lining you up for the
        // boat-ramp cut's split zone just past it.
        {
          kind: 'boostPad',
          id: 'pad-marina-run',
          s0: 230,
          s1: 236,
          d0: 2.5,
          d1: 4.5,
          params: { boostMps: 8, holdS: 1.5, slot: 'keys-pad-marina' },
        },
        // Playtest 1c item 2: the marina pad's other spot (the race seed picks one), mid-lane on the
        // straight before the split, where it does not line you up for the cut.
        {
          kind: 'boostPad',
          id: 'pad-marina-run-early',
          s0: 150,
          s1: 156,
          d0: 0.5,
          d1: 3,
          params: { boostMps: 8, holdS: 1.5, slot: 'keys-pad-marina' },
        },
      ],
      barriers: [],
    },
    {
      id: 'c-marina-split-main',
      name: 'Marina split',
      connector: true,
      lengthM: 30,
      speedLimitMps: 24.6,
      surface: 'asphalt',
      humps: [],
      tags: [
        { s0: 0, s1: 'end', side: 'both', tag: 'marina' },
        { s0: 0, s1: 'end', side: 'both', tag: 'key-fishing' },
      ],
      features: [],
      barriers: [],
    },
    {
      id: 'm1-marina-bends',
      name: 'Marina Bends',
      lengthM: 840,
      speedLimitMps: 24.6,
      surface: 'asphalt',
      humps: [{ centreM: 430, lengthM: 220, heightM: 2.5 }],
      // W-Q: the fishing village's waterfront runs the whole left side of the bends.
      tags: [
        { s0: 0, s1: 'end', side: 'left', tag: 'marina' },
        { s0: 0, s1: 190, side: 'right', tag: 'strip-mall' },
        { s0: 190, s1: 'end', side: 'right', tag: 'palms' },
        { s0: 0, s1: 'end', side: 'both', tag: 'key-fishing' },
      ],
      features: [
        {
          kind: 'billboard',
          id: 'sign-bends-live-bait',
          s0: 120,
          s1: 130,
          d0: 6.5,
          d1: 9,
          item: 'live-bait',
        },
        {
          kind: 'billboard',
          id: 'sign-bends-shrimp-boats',
          s0: 520,
          s1: 530,
          d0: -9,
          d1: -6.5,
          item: 'shrimp-boats',
        },
        {
          kind: 'billboard',
          id: 'sign-bends-conch-republic',
          s0: 195,
          s1: 205,
          d0: -9,
          d1: -6.5,
          item: 'conch-republic',
        },
        {
          kind: 'billboard',
          id: 'sign-bends-hurricane',
          s0: 250,
          s1: 260,
          d0: 6.5,
          d1: 9,
          item: 'hurricane-late',
        },
        {
          kind: 'billboard',
          id: 'bb-bends-landfall',
          s0: 290,
          s1: 330,
          d0: 7,
          d1: 16,
          item: 'landfall-liquors',
        },
        {
          kind: 'billboard',
          id: 'bb-bends-law-office',
          s0: 380,
          s1: 420,
          d0: -16,
          d1: -7,
          item: 'law-office-nobody',
        },
        { kind: 'billboard', id: 'bb-bends-flat-calm', s0: 450, s1: 490, d0: 7, d1: 16, item: 'flat-calm' },
        {
          kind: 'billboard',
          id: 'sign-bends-key-lime',
          s0: 560,
          s1: 570,
          d0: 6.5,
          d1: 9,
          item: 'key-lime-again',
        },
        {
          kind: 'billboard',
          id: 'bb-bends-lobster',
          s0: 620,
          s1: 660,
          d0: 7,
          d1: 16,
          item: 'lobster-lotion',
        },
        {
          kind: 'billboard',
          id: 'bb-bends-airboat',
          s0: 740,
          s1: 780,
          d0: -16,
          d1: -7,
          item: 'airboat-gary',
        },
        {
          kind: 'roadsideZone',
          id: 'marina-boardwalk',
          s0: 50,
          s1: 150,
          d0: -12.6,
          d1: -5.6,
          params: { spawns: 'pedestrians' },
        },
      ],
      barriers: [],
    },
    {
      id: 'c-marina-merge-main',
      name: 'Marina merge',
      connector: true,
      lengthM: 30,
      speedLimitMps: 24.6,
      surface: 'asphalt',
      humps: [],
      tags: [{ s0: 0, s1: 'end', side: 'both', tag: 'palms' }],
      features: [],
      barriers: [],
    },
    {
      id: 'm1-pelican-bridge',
      name: 'Pelican Channel Bridge',
      lengthM: 1250,
      speedLimitMps: 24.6,
      surface: 'asphalt',
      humps: [
        { centreM: 420, lengthM: 380, heightM: 8 },
        { centreM: 950, lengthM: 260, heightM: 4.5 },
      ],
      tags: [
        { s0: 0, s1: 'end', side: 'both', tag: 'bridge' },
        { s0: 0, s1: 'end', side: 'both', tag: 'water-open' },
      ],
      features: [
        {
          kind: 'roadsideZone',
          id: 'fishing-rail',
          s0: 680,
          s1: 780,
          d0: -7.1,
          d1: -5.5,
          params: { spawns: 'pedestrians' },
        },
        // road-3: a road sign at the foot of the bridge, just outside the right-hand rail.
        {
          kind: 'billboard',
          id: 'sign-bridge-ices',
          s0: 20,
          s1: 30,
          d0: 6.5,
          d1: 9,
          item: 'ices-before-road',
        },
        // Playtest 1b quick wins, on the flat between the humps: a car-carrier tow truck parked on
        // the right shoulder, its rear deck down as a ramp. Ride up the deck, fly. The truck's box
        // stops 0.2 m clear of the widest traffic vehicle in the right lane, and the flight lands
        // before the second hump at 44.7 m/s. No boost pad feeds it: boosted to 52.7 m/s, the
        // 13.7° deck throws a bike 11 m up and it lands hard enough to wobble.
        {
          kind: 'rampTruck',
          id: 'carrier-bridge-flat',
          s0: 620,
          s1: 642,
          d0: 3.4,
          d1: 5.4,
          params: { rampLengthM: 11.5, lipHeightM: 2.8, slot: 'keys-truck' },
        },
        // Playtest 1c item 2: the truck's other spot on the bridge, on the flat past the second hump,
        // landing before the bridge ends. No pad candidate is within 400 m before any truck spot.
        {
          kind: 'rampTruck',
          id: 'carrier-bridge-far',
          s0: 1090,
          s1: 1112,
          d0: 3.4,
          d1: 5.4,
          params: { rampLengthM: 11.5, lipHeightM: 2.8, slot: 'keys-truck' },
        },
      ],
      barriers: [{ s0: 0, s1: 'end', side: 'both', kind: 'rail', heightM: 1 }],
    },
    {
      id: 'm1-sandbar-causeway',
      name: 'Sandbar Causeway',
      lengthM: 1180,
      speedLimitMps: 24.6,
      surface: 'asphalt',
      humps: [{ centreM: 560, lengthM: 240, heightM: 4 }],
      // W-Q: over the bridge is Lime Wedge Key, the resort strip (`key-resort`: pastel hotels,
      // pools, tiki bars, rental scooters) on a beach that now runs to s 900.
      tags: [
        { s0: 0, s1: 'end', side: 'both', tag: 'causeway' },
        { s0: 0, s1: 900, side: 'right', tag: 'beach' },
        { s0: 0, s1: 'end', side: 'left', tag: 'water-shallow' },
        { s0: 900, s1: 'end', side: 'right', tag: 'mangrove' },
        { s0: 0, s1: 'end', side: 'both', tag: 'key-resort' },
      ],
      features: [
        {
          kind: 'billboard',
          id: 'sign-causeway-lime-wedge',
          s0: 20,
          s1: 30,
          d0: 6.5,
          d1: 9,
          item: 'lime-wedge-key',
        },
        {
          kind: 'billboard',
          id: 'sign-causeway-scooters',
          s0: 470,
          s1: 480,
          d0: 6.5,
          d1: 9,
          item: 'scooter-rentals',
        },
        {
          kind: 'billboard',
          id: 'bb-causeway-pastel-palms',
          s0: 540,
          s1: 580,
          d0: 7,
          d1: 16,
          item: 'pastel-palms',
        },
        {
          kind: 'billboard',
          id: 'sign-causeway-pool-hours',
          s0: 640,
          s1: 650,
          d0: 6.5,
          d1: 9,
          item: 'pool-hours',
        },
        {
          kind: 'billboard',
          id: 'bb-causeway-tiki-tims',
          s0: 720,
          s1: 760,
          d0: 7,
          d1: 16,
          item: 'tiki-tims',
        },
        { kind: 'billboard', id: 'sign-causeway-uv', s0: 100, s1: 110, d0: 6.5, d1: 9, item: 'uv-index' },
        {
          kind: 'billboard',
          id: 'sign-causeway-iguanas',
          s0: 380,
          s1: 390,
          d0: 6.5,
          d1: 9,
          item: 'iguana-right-of-way',
        },
        {
          kind: 'billboard',
          id: 'sign-causeway-next-county',
          s0: 290,
          s1: 300,
          d0: 6.5,
          d1: 9,
          item: 'next-county',
        },
        {
          kind: 'roadsideZone',
          id: 'sandbar-beach',
          s0: 150,
          s1: 260,
          d0: 5.6,
          d1: 14.6,
          params: { spawns: 'pedestrians' },
        },
        // road-3: the streaming outfit's billboard over the beach.
        {
          kind: 'billboard',
          id: 'bb-causeway-stream',
          s0: 320,
          s1: 360,
          d0: 7,
          d1: 16,
          item: 'stream-outfit',
        },
        {
          kind: 'roadsideZone',
          id: 'tiki-stand',
          s0: 820,
          s1: 900,
          d0: -12.6,
          d1: -5.6,
          params: { spawns: 'pedestrians' },
        },
        // Playtest 1b quick wins: a boost pad in the right lane off the bridge (the causeway's hump
        // is gentle enough not to launch a boosted bike), and a last one for the sprint to the line.
        {
          kind: 'boostPad',
          id: 'pad-causeway-start',
          s0: 40,
          s1: 46,
          d0: 0.5,
          d1: 3,
          params: { boostMps: 8, holdS: 1.5, slot: 'keys-pad-causeway' },
        },
        {
          kind: 'boostPad',
          id: 'pad-causeway-sprint',
          s0: 1040,
          s1: 1046,
          d0: 0.5,
          d1: 3,
          params: { boostMps: 8, holdS: 1.5, slot: 'keys-pad-sprint' },
        },
        // Playtest 1c item 2: each causeway pad's other spot (the race seed picks one). The causeway
        // has no straight long enough for the truck's flight, so its spots are both on the bridge.
        {
          kind: 'boostPad',
          id: 'pad-causeway-beach',
          s0: 280,
          s1: 286,
          d0: 0.5,
          d1: 3,
          params: { boostMps: 8, holdS: 1.5, slot: 'keys-pad-causeway' },
        },
        {
          kind: 'boostPad',
          id: 'pad-causeway-sprint-early',
          s0: 960,
          s1: 966,
          d0: 0.5,
          d1: 3,
          params: { boostMps: 8, holdS: 1.5, slot: 'keys-pad-sprint' },
        },
      ],
      barriers: [],
    },
    // road-3: the standard and long race lengths carry on from here.
    {
      id: 'm1-mangrove-cut',
      name: 'Mangrove Cut',
      lengthM: 1250,
      speedLimitMps: 24.6,
      surface: 'asphalt',
      humps: [{ centreM: 900, lengthM: 200, heightM: 2 }],
      tags: [
        { s0: 0, s1: 'end', side: 'both', tag: 'mangrove' },
        { s0: 0, s1: 600, side: 'left', tag: 'swamp' },
        { s0: 900, s1: 'end', side: 'right', tag: 'water-shallow' },
      ],
      features: [],
      barriers: [],
    },
    {
      // Run W-R: the sandbar's split, Tarpon Flats' first 30 m.
      id: 'c-sandbar-flats-split-main',
      name: 'Sandbar split',
      connector: true,
      lengthM: 30,
      speedLimitMps: 24.6,
      surface: 'asphalt',
      humps: [],
      tags: [
        { s0: 0, s1: 'end', side: 'left', tag: 'water-shallow' },
        { s0: 0, s1: 'end', side: 'right', tag: 'beach' },
        { s0: 0, s1: 'end', side: 'both', tag: 'key-junkyard' },
      ],
      features: [],
      barriers: [],
    },
    {
      id: 'm1-tarpon-flats',
      name: 'Tarpon Flats',
      // Run W-R: 60 m shorter (the sandbar's split and merge, 30 m each end); every s is 30 m less.
      lengthM: 1190,
      speedLimitMps: 24.6,
      surface: 'asphalt',
      humps: [],
      // W-Q: past the mangroves is Salvage Key, the junkyard key (`key-junkyard`: boats racked
      // three high, retired buses stacked, a junk-art garden) on a lot that starts at s 250.
      tags: [
        { s0: 0, s1: 'end', side: 'left', tag: 'water-shallow' },
        { s0: 0, s1: 220, side: 'right', tag: 'beach' },
        { s0: 220, s1: 'end', side: 'right', tag: 'trailer-park' },
        { s0: 0, s1: 'end', side: 'both', tag: 'key-junkyard' },
      ],
      features: [
        {
          kind: 'billboard',
          id: 'sign-flats-salvage-key',
          // Run W-R: at the flats' new start (its old spot, s 20, is in the sandbar's split now).
          s0: 0,
          s1: 10,
          d0: 6.5,
          d1: 9,
          item: 'salvage-key',
        },
        {
          kind: 'billboard',
          id: 'sign-flats-sculpture',
          s0: 490,
          s1: 500,
          d0: 6.5,
          d1: 9,
          item: 'sculpture-garden',
        },
        {
          kind: 'billboard',
          id: 'sign-flats-boats',
          s0: 770,
          s1: 780,
          d0: 6.5,
          d1: 9,
          item: 'boats-for-sale',
        },
        {
          kind: 'billboard',
          id: 'bb-flats-big-rays',
          s0: 970,
          s1: 1010,
          d0: 7,
          d1: 16,
          item: 'big-rays',
        },
        {
          kind: 'roadsideZone',
          id: 'flats-anglers',
          s0: 270,
          s1: 370,
          d0: 5.6,
          d1: 12.6,
          params: { spawns: 'pedestrians' },
        },
      ],
      barriers: [],
    },
    {
      // Run W-R: the sandbar's merge, Tarpon Flats' last 30 m.
      id: 'c-sandbar-flats-merge-main',
      name: 'Sandbar merge',
      connector: true,
      lengthM: 30,
      speedLimitMps: 24.6,
      surface: 'asphalt',
      humps: [],
      tags: [
        { s0: 0, s1: 'end', side: 'left', tag: 'water-shallow' },
        { s0: 0, s1: 'end', side: 'right', tag: 'trailer-park' },
        { s0: 0, s1: 'end', side: 'both', tag: 'key-junkyard' },
      ],
      features: [],
      barriers: [],
    },
    {
      id: 'm1-conch-row',
      name: 'Conch Row',
      lengthM: 1300,
      speedLimitMps: 24.6,
      surface: 'asphalt',
      humps: [{ centreM: 1050, lengthM: 220, heightM: 2.5 }],
      tags: [
        { s0: 0, s1: 900, side: 'both', tag: 'town' },
        { s0: 900, s1: 'end', side: 'left', tag: 'strip-mall' },
        { s0: 900, s1: 'end', side: 'right', tag: 'trailer-park' },
      ],
      features: [
        {
          kind: 'roadsideZone',
          id: 'conch-row-sidewalk',
          s0: 200,
          s1: 300,
          d0: -12.6,
          d1: -5.6,
          params: { spawns: 'pedestrians' },
        },
      ],
      barriers: [],
    },
    {
      id: 'm1-long-bridge',
      name: 'Almost Seven Mile Bridge',
      lengthM: 2300,
      speedLimitMps: 24.6,
      surface: 'asphalt',
      humps: [
        { centreM: 500, lengthM: 400, heightM: 9 },
        { centreM: 1300, lengthM: 600, heightM: 12 },
        { centreM: 1950, lengthM: 300, heightM: 5 },
      ],
      tags: [
        { s0: 0, s1: 'end', side: 'both', tag: 'bridge' },
        { s0: 0, s1: 'end', side: 'both', tag: 'water-open' },
      ],
      features: [
        {
          kind: 'roadsideZone',
          id: 'long-bridge-fishing-rail',
          s0: 1700,
          s1: 1800,
          d0: -7.1,
          d1: -5.5,
          params: { spawns: 'pedestrians' },
        },
      ],
      barriers: [{ s0: 0, s1: 'end', side: 'both', kind: 'rail', heightM: 1 }],
    },
    {
      id: 'm1-last-resort-causeway',
      name: 'Last Resort Causeway',
      speedLimitMps: 24.6,
      surface: 'asphalt',
      humps: [{ centreM: 700, lengthM: 240, heightM: 4 }],
      // W-Q: the long haul ends on Last Resort Key, the party key the morning after (`key-party`:
      // bunting, coolers left where they fell, the closed bar, a deflated flamingo), its beach the
      // whole left side.
      tags: [
        { s0: 0, s1: 'end', side: 'both', tag: 'causeway' },
        { s0: 0, s1: 'end', side: 'left', tag: 'beach' },
        { s0: 0, s1: 600, side: 'right', tag: 'water-shallow' },
        { s0: 600, s1: 'end', side: 'right', tag: 'mangrove' },
        { s0: 0, s1: 'end', side: 'both', tag: 'key-party' },
      ],
      features: [
        {
          kind: 'billboard',
          id: 'sign-resort-last-resort-key',
          s0: 30,
          s1: 40,
          d0: -9,
          d1: -6.5,
          item: 'last-resort-key',
        },
        {
          kind: 'billboard',
          id: 'bb-resort-hair-of-the-dog',
          s0: 300,
          s1: 340,
          d0: -16,
          d1: -7,
          item: 'hair-of-the-dog',
        },
        {
          kind: 'billboard',
          id: 'sign-resort-bar-closed',
          s0: 600,
          s1: 610,
          d0: -9,
          d1: -6.5,
          item: 'bar-closed',
        },
        {
          kind: 'billboard',
          id: 'sign-resort-flamingo',
          s0: 900,
          s1: 910,
          d0: -9,
          d1: -6.5,
          item: 'flamingo-found',
        },
        {
          kind: 'billboard',
          id: 'bb-resort-sunset-fest',
          s0: 1100,
          s1: 1140,
          d0: -16,
          d1: -7,
          item: 'sunset-fest',
        },
      ],
      barriers: [],
    },
  ],
  branches: [
    {
      // Run W-R (interview, 2026-10-02: marked dirt shortcuts, "sandbars"): the Sandbar Flats, a sand
      // track across the shallows north of Tarpon Flats, off the left at the end of the Mangrove Cut
      // and back at the foot of Conch Row: shorter, loose, over a hummock, with the junkyard key on
      // the other side of the water. Every route that reaches its split takes it too (the short
      // sprint ends before it). Keep left at the end of the mangroves to take it.
      leave: {
        road: 'm1-mangrove-cut',
        offsetM: -4,
        lane: 'L1',
        zone: { lengthM: 40, d0: -5.5, d1: -3 },
      },
      join: { road: 'm1-conch-row', offsetM: -3, lane: 'L1' },
      turnsM: [600, 150],
      lanes: [{ id: 'S1', dCenterM: 0, widthM: 5, direction: 1, kind: 'shortcut' }],
      // Named for the routes (W-R): the id it would derive, written into every route that allows it.
      named: {
        id: 'm1-sandbar-flats',
        kind: 'shortcut',
        marked: true,
        sign: 'SANDBAR: NOT ADVISED. Advice not taken.',
      },
      roads: [
        {
          id: 'c-sandbar-flats-in',
          name: 'Sandbar ramp',
          connector: true,
          lengthM: 30,
          speedLimitMps: 24.6,
          surface: 'sand',
          humps: [],
          tags: [{ s0: 0, s1: 'end', side: 'both', tag: 'beach' }],
          features: [],
          barriers: [],
        },
        {
          id: 'm1-sandbar-flats',
          name: 'Sandbar Flats',
          speedLimitMps: 24.6,
          surface: 'sand',
          humps: [],
          ramps: [{ id: 'hummock', s0: 400, lengthM: 15, heightM: 1.5, backM: 5 }],
          tags: [{ s0: 0, s1: 'end', side: 'both', tag: 'beach' }],
          features: [
            // The deadpan sign at the top of the sandbar, past the sand band, on the beach.
            {
              kind: 'billboard',
              id: 'sign-sandbar-advised',
              s0: 30,
              s1: 40,
              d0: 9.5,
              d1: 12,
              item: 'sandbar-not-advised',
            },
          ],
          barriers: [],
        },
        {
          id: 'c-sandbar-flats-out',
          name: 'Sandbar exit',
          connector: true,
          lengthM: 30,
          speedLimitMps: 24.6,
          surface: 'sand',
          humps: [],
          tags: [{ s0: 0, s1: 'end', side: 'both', tag: 'beach' }],
          features: [],
          barriers: [],
        },
      ],
    },
    {
      // The boat-ramp cut: a gravelly service lane through the boat yard, straight up the east
      // side of the S-bends, over one launch ramp. Hug the right edge before the split to take it.
      leave: {
        road: 'm1-marina-run',
        offsetM: 4,
        lane: 'R1',
        zone: { lengthM: 40, d0: 3, d1: 5.5 },
      },
      join: { road: 'm1-pelican-bridge', offsetM: 3, lane: 'R1' },
      turnsM: [60, 60],
      lanes: [{ id: 'S1', dCenterM: 0, widthM: 5, direction: 1, kind: 'shortcut' }],
      // Named for the routes (W-R): the id the race derived before, so nothing keyed on it changes.
      named: {
        id: 'm1-boat-ramp-cut',
        kind: 'shortcut',
        marked: true,
        sign: 'BOAT RAMP: KEEP RIGHT. Trailers only. Nobody checks.',
      },
      roads: [
        {
          id: 'c-boat-ramp-in',
          name: 'Boat yard gate',
          connector: true,
          lengthM: 30,
          speedLimitMps: 24.6,
          surface: 'asphalt',
          humps: [],
          tags: [
            { s0: 0, s1: 'end', side: 'both', tag: 'marina' },
            { s0: 0, s1: 'end', side: 'both', tag: 'key-fishing' },
          ],
          features: [],
          barriers: [],
        },
        {
          id: 'm1-boat-ramp-cut',
          name: 'Boat Ramp Cut',
          speedLimitMps: 24.6,
          surface: 'asphalt',
          humps: [],
          ramps: [{ id: 'boat-ramp', s0: 400, lengthM: 15, heightM: 1.5, backM: 5 }],
          tags: [
            { s0: 0, s1: 'end', side: 'both', tag: 'marina' },
            { s0: 300, s1: 'end', side: 'right', tag: 'water-shallow' },
            { s0: 0, s1: 'end', side: 'both', tag: 'key-fishing' },
          ],
          features: [
            // W-Q: the boat yard's own billboard, for whoever takes the cut.
            {
              kind: 'billboard',
              id: 'bb-cut-trap-line',
              s0: 150,
              s1: 190,
              d0: 7,
              d1: 16,
              item: 'trap-line',
            },
          ],
          barriers: [],
        },
        {
          id: 'c-boat-ramp-out',
          name: 'Boat yard exit',
          connector: true,
          lengthM: 30,
          speedLimitMps: 24.6,
          surface: 'asphalt',
          humps: [],
          tags: [{ s0: 0, s1: 'end', side: 'both', tag: 'palms' }],
          features: [],
          barriers: [],
        },
      ],
    },
  ],
  routes: [
    {
      id: 'm1-skeleton-sprint',
      start: { road: 'm1-marina-run', s: 40, dir: 1 },
      finish: { road: 'm1-sandbar-causeway', s: -40 },
      // On roads both paths share, so a shortcut rider passes them too.
      checkpoints: [
        { road: 'm1-pelican-bridge', s: 300 },
        { road: 'm1-pelican-bridge', s: 1000 },
        { road: 'm1-sandbar-causeway', s: 500 },
      ],
      startGrid: { rows: 3, perRow: 2, rowGapM: 8 },
    },
    {
      // road-3: the standard length, to the end of Conch Row.
      id: 'm1-standard-run',
      start: { road: 'm1-marina-run', s: 40, dir: 1 },
      finish: { road: 'm1-conch-row', s: -40 },
      checkpoints: [
        { road: 'm1-pelican-bridge', s: 300 },
        { road: 'm1-pelican-bridge', s: 1000 },
        { road: 'm1-sandbar-causeway', s: 500 },
        { road: 'm1-mangrove-cut', s: 600 },
        // Run W-R: none on Tarpon Flats, which the sandbar skips.
        { road: 'm1-conch-row', s: 600 },
      ],
      startGrid: { rows: 3, perRow: 2, rowGapM: 8 },
    },
    {
      // road-3: the long length, over the long bridge to the Last Resort Causeway.
      id: 'm1-long-haul',
      start: { road: 'm1-marina-run', s: 40, dir: 1 },
      finish: { road: 'm1-last-resort-causeway', s: -40 },
      checkpoints: [
        { road: 'm1-pelican-bridge', s: 300 },
        { road: 'm1-pelican-bridge', s: 1000 },
        { road: 'm1-sandbar-causeway', s: 500 },
        { road: 'm1-mangrove-cut', s: 600 },
        // Run W-R: none on Tarpon Flats, which the sandbar skips.
        { road: 'm1-conch-row', s: 600 },
        { road: 'm1-long-bridge', s: 1150 },
        { road: 'm1-last-resort-causeway', s: 500 },
      ],
      startGrid: { rows: 3, perRow: 2, rowGapM: 8 },
    },
  ],
};
