// The base pack, bundled into the build (docs/content-packs.md, "The base game as pack zero").
// Vite's import.meta.glob is the generated index here: the bundler lists every JSON file under
// packs/base at build time, so nothing is hand-maintained and a static host never lists folders.
// The pack.index.json with sizes and hashes is generated by tools/packs (never committed).
import type { AssetIndexEntry } from '../core';
import type { PackFile } from './parse';
import { buildRegistry, ContentError, type ContentRegistry, type LoadOptions } from './registry';

/**
 * Every base file except its road data (networks, roads and routes) and its asset data files.
 * - The `osm-*` real-road data (the Bahia Honda run, run W-P) is fetched on demand like a region
 *   pack's roads (packs.ts).
 * - The hand-made Keys road data (run W-S, the first-load JavaScript budget: about 100 KB of its
 *   500 KB gzip) ships as JSON files beside the build too, and boot fetches it before the app starts
 *   (`loadBaseRoads`), since the default race and the menu's backdrop need it at once.
 * - Asset data files (`assets/**`, such as the backdrop's) are not entries: whoever needs one loads
 *   it on demand, as the other packs' are (packs.ts), so none rides in the first load.
 */
const RAW = import.meta.glob<unknown>(
  [
    '/packs/base/**/*.json',
    '!/packs/base/regions/*/networks/**',
    '!/packs/base/regions/*/roads/**',
    '!/packs/base/regions/*/routes/**',
    '!/packs/base/assets/**',
  ],
  { eager: true, import: 'default' },
);
/** The hand-made Keys road data's URLs (not the `osm-*` files: packs.ts fetches those). */
const ROAD_URLS = import.meta.glob<string>(
  [
    '/packs/base/regions/*/networks/*.json',
    '/packs/base/regions/*/roads/*.json',
    '/packs/base/regions/*/routes/*.json',
    '!/packs/base/regions/*/networks/osm-*.json',
    '!/packs/base/regions/*/roads/osm-*.json',
    '!/packs/base/regions/*/routes/osm-*.json',
  ],
  { eager: true, query: '?url', import: 'default' },
);
/**
 * Every pack's baked models (playtest 1c item 4): the bundler emits each GLB into the build and
 * gives its URL, so the files ship with the game and load through the asset manifest by id. A
 * region's own models sit in its region pack (tools/blender/README.md, "Pack and region"; playtest 3:
 * the landmark kits and the step-up bikes), so the glob covers every pack, and only a URL string per
 * model rides in the first load: a file is fetched when something loads its id.
 */
const MODEL_URLS = import.meta.glob<string>('/packs/*/assets/**/*.glb', {
  eager: true,
  query: '?url',
  import: 'default',
});

const packPath = (key: string) => key.replace(/^\/packs\/base\//, '');

/**
 * The asset manifest rows the registry's packs contribute (docs/architecture.md, "Asset
 * manifest"): each carried pack's GLBs, by asset id (the path under the pack's assets/ without its
 * extension), with the pack's id. A pack the registry does not carry contributes none.
 * `path` is the bundler's URL for the file, which the manifest resolves against the page. `bytes`
 * and `hash` stay 0 and '' in the build: the core contract allows that until the indexer's sizes
 * and hashes reach the runtime (tools/packs writes them to pack.index.json, never committed).
 */
export function assetIndex(reg: ContentRegistry): readonly AssetIndexEntry[] {
  const carried = new Set(reg.packs.map((p) => p.id));
  return Object.keys(MODEL_URLS)
    .sort()
    .flatMap((key) => {
      const m = /^\/packs\/([^/]+)\/assets\/(.+)$/.exec(key);
      if (!m || !carried.has(m[1] as string)) return [];
      return [
        {
          id: (m[2] as string).replace(/\.[^./]+$/, ''),
          kind: 'mesh' as const,
          source: 'baked' as const,
          path: MODEL_URLS[key] ?? key,
          bytes: 0,
          hash: '',
          packId: m[1] as string,
        },
      ];
    });
}

// ---- The hand-made Keys road data, fetched at boot ---------------------------------------------

let roads: readonly PackFile[] | null = null;
/** The bundled base pack's registry, once built (per option set). */
let cached: ContentRegistry | null = null;
let cachedDrafts: boolean | null = null;
let roadsLoading: Promise<void> | null = null;

async function fetchJson(url: string): Promise<unknown> {
  const res = await fetch(url);
  if (!res.ok) throw new ContentError(`could not load ${url}: HTTP ${res.status}`);
  return (await res.json()) as unknown;
}

/** Fetches the hand-made Keys road data, every file at once, in path order (pure: stores nothing). */
export async function fetchBaseRoads(
  load: (url: string) => Promise<unknown> = fetchJson,
): Promise<PackFile[]> {
  const keys = Object.keys(ROAD_URLS).sort();
  return Promise.all(
    keys.map(async (key) => ({ path: packPath(key), json: await load(ROAD_URLS[key] ?? key) })),
  );
}

/**
 * Gives the base pack its hand-made road data (pack-relative paths). Boot does it through
 * `loadBaseRoads`; Node-side callers (the test setup, the build's self-test race) pass the files
 * from disk (`provideBaseRoadsFromDisk` in base-pack-whole.ts).
 */
export function provideBaseRoads(files: readonly PackFile[]): void {
  roads = [...files];
  cached = null;
}

/** True once the hand-made road data is in, so `loadBasePack()` can be called. */
export function baseRoadsLoaded(): boolean {
  return roads !== null;
}

/**
 * Fetches the hand-made road data once (boot awaits this before the app starts). A failed fetch
 * rejects and can be tried again (a dropped connection on the phone).
 */
export function loadBaseRoads(): Promise<void> {
  if (roads) return Promise.resolve();
  roadsLoading ??= fetchBaseRoads().then(
    (files) => {
      if (!roads) provideBaseRoads(files);
    },
    (err: unknown) => {
      roadsLoading = null;
      throw err;
    },
  );
  return roadsLoading;
}

/**
 * The base pack's bundled files as parsed JSON, with pack-relative paths, in path order: its
 * entries and its hand-made road data, without its real-road data (`isRealRoadPath`), which the
 * pack library fetches on demand. The same files in the same order as when the roads were bundled,
 * so the registry, both content hashes and every replay key are unchanged.
 */
export function basePackFiles(): PackFile[] {
  if (!roads)
    throw new ContentError(
      "the base pack's hand-made road data is not loaded yet: boot awaits loadBaseRoads() first",
    );
  const entries = Object.keys(RAW).map((key) => ({ path: packPath(key), json: RAW[key] }));
  return [...entries, ...roads].sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
}

/**
 * Loads, validates and freezes the bundled base pack (once per option set): without its real-road
 * data. A caller that needs the Bahia Honda run uses the pack library or `registryFromGlob`.
 * It needs the hand-made road data in (`loadBaseRoads`), and says so when it is not.
 */
export function loadBasePack(options: LoadOptions = {}): ContentRegistry {
  const drafts = options.includeDrafts ?? false;
  if (!cached || cachedDrafts !== drafts) {
    cached = buildRegistry(basePackFiles(), { includeDrafts: drafts });
    cachedDrafts = drafts;
  }
  return cached;
}
