// The base pack, bundled into the build (docs/content-packs.md, "The base game as pack zero").
// Vite's import.meta.glob is the generated index here: the bundler lists every JSON file under
// packs/base at build time, so nothing is hand-maintained and a static host never lists folders.
// The pack.index.json with sizes and hashes is generated by tools/packs (never committed).
import type { AssetIndexEntry } from '../core';
import type { PackFile } from './parse';
import { buildRegistry, type ContentRegistry, type LoadOptions } from './registry';

/**
 * Every base file except its real-road data (run W-P): the `osm-*` networks, roads and routes (the
 * Bahia Honda run) are fetched on demand like a region pack's roads (packs.ts), so the first load
 * carries only the hand-made Keys roads the default race and the menu need. Asset data files
 * (`assets/**`, such as the backdrop's) are not entries: whoever needs one loads it on demand, as
 * the other packs' are (packs.ts), so none rides in the first load.
 */
const RAW = import.meta.glob<unknown>(
  [
    '/packs/base/**/*.json',
    '!/packs/base/regions/*/networks/osm-*.json',
    '!/packs/base/regions/*/roads/osm-*.json',
    '!/packs/base/regions/*/routes/osm-*.json',
    '!/packs/base/assets/**',
  ],
  { eager: true, import: 'default' },
);
/**
 * The base pack's baked models (playtest 1c item 4): the bundler emits each GLB into the build and
 * gives its URL, so the files ship with the game and load through the asset manifest by id.
 */
const MODEL_URLS = import.meta.glob<string>('/packs/base/assets/**/*.glb', {
  eager: true,
  query: '?url',
  import: 'default',
});

/**
 * The asset manifest rows the registry's packs contribute (docs/architecture.md, "Asset
 * manifest"): the base pack's GLBs, by asset id (the path under assets/ without its extension).
 * `path` is the bundler's URL for the file, which the manifest resolves against the page. `bytes`
 * and `hash` stay 0 and '' in the build: the core contract allows that until the indexer's sizes
 * and hashes reach the runtime (tools/packs writes them to pack.index.json, never committed).
 */
export function assetIndex(reg: ContentRegistry): readonly AssetIndexEntry[] {
  if (!reg.packs.some((p) => p.id === 'base')) return [];
  return Object.keys(MODEL_URLS)
    .sort()
    .map((key) => {
      const rel = key.replace(/^\/packs\/base\/assets\//, '');
      return {
        id: rel.replace(/\.[^./]+$/, ''),
        kind: 'mesh' as const,
        source: 'baked' as const,
        path: MODEL_URLS[key] ?? key,
        bytes: 0,
        hash: '',
        packId: 'base',
      };
    });
}

/**
 * The base pack's bundled files as parsed JSON, with pack-relative paths, in path order: all but
 * its real-road data (`isRealRoadPath`), which the pack library fetches on demand.
 */
export function basePackFiles(): PackFile[] {
  return Object.keys(RAW)
    .sort()
    .map((key) => ({ path: key.replace(/^\/packs\/base\//, ''), json: RAW[key] }));
}

let cached: ContentRegistry | null = null;
let cachedDrafts: boolean | null = null;

/**
 * Loads, validates and freezes the bundled base pack (once per option set): without its real-road
 * data. A caller that needs the Bahia Honda run uses the pack library or `registryFromGlob`.
 */
export function loadBasePack(options: LoadOptions = {}): ContentRegistry {
  const drafts = options.includeDrafts ?? false;
  if (!cached || cachedDrafts !== drafts) {
    cached = buildRegistry(basePackFiles(), { includeDrafts: drafts });
    cachedDrafts = drafts;
  }
  return cached;
}
