// The structures' parts are the committed models' drawn shapes (the physical world, the maintainer,
// 2026-10-06: "everything a rider can reach is physical at its drawn shape"). scripts/hitboxes.test.ts's twin:
// it holds each model's whole box (road/structures.ts `STRUCTURE_MODELS`) to its file; this holds the parts a
// plan stands for it (Old Town's, road/structures/oldtown.ts `OLDTOWN_PARTS`) to the drawn surface. Every point
// of the drawing lies in some part (within PART_TOLERANCE_M: nothing drawn stands outside the solids, so no
// rider passes through a wall or a post), and every face of every part is touched by the drawing inside it
// (within PART_SLACK_M: no part is bigger than what it stands for). Negative controls move and grow a part.
import { writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { LANDMARK_PARTS } from '../src/road/structures/landmark-parts';
import { LANDMARK_FIGURES } from '../src/road/structures/landmarks';
import { OLDTOWN_PARTS, partSolid, type Part } from '../src/road/structures/oldtown';
import { MODEL_ASSETS, type ModelKind } from '../src/render/models';
import { bakeRepoModel } from '../src/render/model-files.test-util';
import { columnParts } from '../src/render/structure-columns.test-util';
import { PART_SOURCES, sourceGeometry } from '../src/render/structure-sources.test-util';
import { holds, landmarkKit, print, surfacePoints, type Solid } from '../src/render/structures.test-util';

/** How far a drawn point may lie outside the parts, m: a hipped roof cut into slices sits this far under it at most. */
const PART_TOLERANCE_M = 0.4;
/** How far a part's face may stand off the drawing inside it, m (the surface is sampled about 0.15 m apart). */
const PART_SLACK_M = 0.3;
/** The surface's sampling step, m. */
const STEP_M = 0.15;

const solidsOf = (parts: readonly Part[]): Solid[] =>
  parts.map((p) => ({ ...partSolid(p, { x: 0, y: 0, z: 0, turn: 0 }), name: p.name }));

async function drawn(id: string) {
  const kinds = new Map(
    Object.entries(MODEL_ASSETS).map(([kind, asset]) => [asset as string, kind as ModelKind]),
  );
  const [asset = '', variant = ''] = id.split('#');
  const kind = kinds.get(asset);
  if (!kind) throw new Error(`${id}: no model kind loads ${asset}`);
  const model = await bakeRepoModel(kind);
  const g = model.variants[Number(variant)];
  if (!g) throw new Error(`${id}: ${kind} has no variant ${variant}`);
  return surfacePoints(g, STEP_M);
}

describe("Old Town's parts are its models' drawn shapes (road/structures/oldtown.ts OLDTOWN_PARTS)", () => {
  it.each(Object.keys(OLDTOWN_PARTS))(
    '%s',
    async (id) => {
      const parts = OLDTOWN_PARTS[id] ?? [];
      const points = await drawn(id);
      const held = holds(solidsOf(parts), points, PART_TOLERANCE_M, PART_SLACK_M);
      print(
        `[examined] ${id}: ${parts.length} parts against ${points.length} points of its surface; the farthest ` +
          `${held.worst.toFixed(2)} m outside them, ${held.loose.length} over ${PART_TOLERANCE_M} m; ${held.slack.length} slack faces`,
      );
      expect(
        held.loose
          .slice(0, 5)
          .map(([q, m]) => `${q.x.toFixed(2)} ${q.y.toFixed(2)} ${q.z.toFixed(2)}: ${m.toFixed(2)}`),
      ).toEqual([]);
      expect(held.slack.map(([n, f, g]) => `${n} ${f} ${g.toFixed(2)}`)).toEqual([]);
    },
    60_000,
  );

  it('a negative control: a part moved 0.5 m, or grown 0.5 m, is found', async () => {
    const id = 'models/scenery/duval-kit#1';
    const parts = OLDTOWN_PARTS[id] ?? [];
    const points = await drawn(id);
    const moved = parts.map((p) => (p.name === 'body' ? { ...p, x0: p.x0 + 0.5, x1: p.x1 + 0.5 } : p));
    const grown = parts.map((p) => (p.name === 'post-0' ? { ...p, z1: p.z1 + 0.5 } : p));
    const a = holds(solidsOf(moved), points, PART_TOLERANCE_M, PART_SLACK_M);
    const b = holds(solidsOf(grown), points, PART_TOLERANCE_M, PART_SLACK_M);
    expect(a.loose.length + a.slack.length).toBeGreaterThan(0);
    expect(b.slack.map(([n, f]) => `${n} ${f}`)).toContain('post-0 +v');
  }, 60_000);
});

/** The table's file, and the header its writer puts on it. */
const TABLE = 'src/road/structures/landmark-parts.ts';
const HEADER = `// Each landmark's solid parts, measured from its drawing: GENERATED by scripts/structure-parts.test.ts (run it
// with UPDATE_STRUCTURE_PARTS=1 after a landmark's model or soup changes, then format), which holds this table to
// the committed files. By \`<kit>#<node>\` (the node render draws) or \`soup#<name>\` (a code-made one), six numbers a
// part: x0, x1, z0, z1, y0, y1 in its own frame at scale 1 (+Z along the road, +Y up), m. How each is cut:
// src/render/structure-sources.test-util.ts.
`;

/** Every source's parts, measured now. */
async function measureAll(): Promise<Record<string, number[]>> {
  const out: Record<string, number[]> = {};
  for (const src of PART_SOURCES) {
    const g = await sourceGeometry(src.id);
    out[src.id] = columnParts(surfacePoints(g, src.options.cell / 3), src.options).flat();
  }
  return out;
}

/** The parts that differ from the table by more than a centimetre: `<id>: <what>`. */
function differences(
  table: Readonly<Record<string, readonly number[]>>,
  now: Record<string, number[]>,
): string[] {
  const off: string[] = [];
  for (const [id, parts] of Object.entries(now)) {
    const row = table[id];
    if (!row) off.push(`${id}: not in the table`);
    else if (row.length !== parts.length)
      off.push(`${id}: ${row.length / 6} parts in the table, ${parts.length / 6} drawn`);
    else
      parts.forEach((v, i) => {
        if (Math.abs(v - (row[i] ?? NaN)) > 0.011)
          off.push(`${id}: part ${Math.floor(i / 6)} number ${i % 6}: ${row[i]} vs ${v}`);
      });
  }
  for (const id of Object.keys(table))
    if (!(id in now)) off.push(`${id}: in the table, measured from nothing`);
  return off;
}

describe("the landmarks' parts are their drawings (road/structures/landmark-parts.ts)", () => {
  it('the table is every landmark drawing, cut into columns', async () => {
    const now = await measureAll();
    if (process.env['UPDATE_STRUCTURE_PARTS']) {
      const body = Object.entries(now)
        .map(([id, parts]) => `  '${id}': [${parts.join(', ')}],`)
        .join('\n');
      writeFileSync(
        TABLE,
        `${HEADER}export const LANDMARK_PARTS: Readonly<Record<string, readonly number[]>> = {\n${body}\n};\n`,
      );
    }
    const off = differences(LANDMARK_PARTS, now);
    const count = Object.values(now).reduce((n, p) => n + p.length / 6, 0);
    print(
      `[examined] ${PART_SOURCES.length} landmark drawings measured again: ${count} parts, ${off.length} off the table by more than 1 cm`,
    );
    expect(off.slice(0, 8)).toEqual([]);
  }, 300_000);

  it('a negative control: a part 2 cm off its drawing is found', () => {
    const [id, row] = Object.entries(LANDMARK_PARTS)[0] ?? [];
    if (!id || !row) throw new Error('an empty table');
    const moved = { [id]: row.map((v, i) => (i === 1 ? v + 0.02 : v)) };
    expect(differences({ [id]: row }, moved)).toHaveLength(1);
  });

  it("the plan's figures are the files' own: the bays' lengths, the Golden Gate's saddles, top and cable entry", async () => {
    const pdx = await landmarkKit('pdx-landmarks');
    const gg = await landmarkKit('golden-gate');
    const extras = (kit: typeof pdx, node: string) =>
      (kit.nodes.get(node) ?? kit.nodes.get(`${node}_lod0`))?.extras;
    for (const [id, bay] of Object.entries(LANDMARK_FIGURES.bayM)) {
      const [kitId = '', node = ''] = id.split('#');
      expect(extras(kitId === 'golden-gate' ? gg : pdx, node)?.['bay_m'], id).toBe(bay);
    }
    expect(extras(gg, 'gg_tower')?.['top_m']).toBe(LANDMARK_FIGURES.ggTopM);
    expect(extras(gg, 'gg_tower')?.['cable_saddle_x_m']).toBe(LANDMARK_FIGURES.ggSaddleXM);
    expect(extras(gg, 'gg_anchorage')?.['cable_entry_m']).toBe(LANDMARK_FIGURES.ggCableEntryM);
    // The Golden Gate's deck edge (its bays, both levels of detail) lies wholly under the deck: no part of the plan.
    for (const node of ['gg_bay_lod0', 'gg_bay_lod1']) {
      const g = gg.nodes.get(node)?.geometry;
      g?.computeBoundingBox();
      expect(g?.boundingBox?.max.y, node).toBeLessThanOrEqual(0.001);
    }
    // Every other drawn node says no bay: render shifts only a bay by half its length.
    for (const src of PART_SOURCES) {
      const [kitId = '', node = ''] = src.id.split('#');
      if (kitId === 'soup' || src.id in LANDMARK_FIGURES.bayM) continue;
      const kit = await landmarkKit(kitId as Parameters<typeof landmarkKit>[0]);
      expect(extras(kit, node)?.['bay_m'], src.id).toBeUndefined();
    }
  }, 120_000);
});
