// The Florida Keys' own models (playtest 3, Codex batch CX2). Every row has `pack: 'base'` (the base
// pack is the Keys' pack) and `region: 'florida-keys'`, so the per-region model budget counts it as
// the Keys' own. CX2 appends here, after the Sport 600's row (playtest 3, T10.1); no other batch edits
// this file.
import { VARIANT_VIEWS, VIEWS } from './views.mjs';

/** @type {import('../catalog.mjs').Prop[]} */
export const KEYS_PROPS = [
  // The Sport 600 (playtest 3, T10.1, "Six bikes"): the Keys' step-up bike, a byte copy of the
  // stickered sport bike under its own id (the rider-look rule draws `models/bikes/<bike id>`).
  // The row reuses that bike's script, so a rebuild writes the same bytes; Codex replaces the
  // script with the bike's own later, under the same name.
  {
    name: 'sport_600',
    script: 'props/sport_stickered.py',
    asset: 'models/bikes/sport-600',
    pack: 'base',
    region: 'florida-keys',
    kind: 'single',
    budget: { tris: 1500, draws: 7, materials: 7 },
    single: {
      root: 'bike',
      nodes: [
        'bike_body',
        'wheel_front',
        'wheel_rear',
        'fork',
        'seat_anchor',
        'bar_l',
        'bar_r',
        'peg_l',
        'peg_r',
        'light_head',
        'light_tail',
      ],
      size: [
        [0.5, 1.4],
        [0.8, 1.8],
        [1.7, 2.7],
      ],
    },
    views: VIEWS,
  },
  {
    name: 'duval_kit',
    script: 'props/duval_kit.py',
    asset: 'models/scenery/duval-kit',
    pack: 'base',
    region: 'florida-keys',
    kind: 'variants',
    budget: { tris: 2140, draws: 110, materials: 17 },
    variants: {
      roots: [
        'duval_balcony_a',
        'duval_balcony_b',
        'duval_balcony_c',
        'duval_conch_a',
        'duval_conch_b',
        'duval_corner_bar',
        'duval_scooter_rack',
        'duval_planter_palm',
      ],
      xs: [-46, -32, -15, 1, 12, 28, 42, 49],
      parts: ['body'],
      perVariant: { tris: 420, draws: 24 },
      tris: [380, 380, 380, 260, 260, 420, 60, 120],
      height: [0, 10],
      heights: [
        [8.8, 9.2],
        [8.8, 9.2],
        [8.8, 9.2],
        [6.8, 7.2],
        [6.8, 7.2],
        [5.8, 6.2],
        [0.98, 1.02],
        [2.4, 2.6],
      ],
      sway: false,
      sharedMaterials: false,
    },
    atlas: {
      sheet: 'florida-keys',
      surfaces: [
        ...['a', 'b', 'c'].flatMap((v, k) => {
          const n = `duval_balcony_${v}`;
          return [
            'siding_0',
            'siding_1',
            'spindles',
            'window_0',
            'window_1',
            'window_2',
            ...Array.from({ length: k === 0 ? 2 : 3 }, (_, i) => `store_${i}`),
            ...Array.from({ length: k === 0 ? 2 : 3 }, (_, i) => `awning_${i}`),
            ...(k === 2 ? ['tin_roof'] : ['tin_roof_l', 'tin_roof_r']),
          ].map((s) => `${n}_${s}`);
        }),
        ...['a', 'b'].flatMap((v) =>
          [
            'siding_0',
            'porch_lattice',
            'door',
            'window_0',
            'window_1',
            'shutter_0',
            'shutter_1',
            'tin_roof_l',
            'tin_roof_r',
          ].map((s) => `duval_conch_${v}_${s}`),
        ),
        'duval_corner_bar_rollup_front',
        'duval_corner_bar_mural',
      ],
    },
    textSurfaces: [
      ...['a', 'b', 'c'].flatMap((v, k) =>
        Array.from({ length: k === 0 ? 2 : 3 }, (_, i) => `duval_balcony_${v}_shop_name_${i}`),
      ),
      'duval_corner_bar_name',
    ],
    convexParts: [],
    views: VARIANT_VIEWS,
  },
  {
    name: 'keys_landmarks',
    script: 'props/keys_landmarks.py',
    asset: 'models/landmarks/keys-landmarks',
    pack: 'base',
    region: 'florida-keys',
    kind: 'variants',
    budget: { materials: 14 },
    variants: {
      roots: [
        'southernmost_buoy',
        'mile_marker_0',
        'mallory_pier',
        'east_martello_lod0',
        'east_martello_lod1',
        'west_martello',
        'cruise_ship_lod0',
        'cruise_ship_lod1',
      ],
      xs: [-22, -15, 12, 68, 123, 170, 280, 335],
      parts: ['body'],
      perVariant: { tris: 800, draws: 8 },
      tris: [300, 60, 800, 700, 210, 500, 500, 150],
      height: [0, 61],
      heights: [
        [3.65, 3.67],
        [1.99, 2.01],
        [4.8, 4.9],
        [11.9, 12.1],
        [11.9, 12.1],
        [3.9, 4.1],
        [59.99, 60.01],
        [59.99, 60.01],
      ],
      sway: false,
      sharedMaterials: false,
      lods: [
        { lod0: 'east_martello_lod0', lod1: 'east_martello_lod1' },
        { lod0: 'cruise_ship_lod0', lod1: 'cruise_ship_lod1' },
      ],
    },
    textSurfaces: ['southernmost_buoy_text', 'mile_marker_0_face'],
    convexParts: [],
    views: VARIANT_VIEWS,
  },
  {
    name: 'seven_mile_kit',
    script: 'props/seven_mile_kit.py',
    asset: 'models/scenery/seven-mile-kit',
    pack: 'base',
    region: 'florida-keys',
    kind: 'variants',
    budget: { materials: 9 },
    variants: {
      roots: [
        'nsm_bay',
        'nsm_bay_tall',
        'osm_arch_bay',
        'osm_girder_bay',
        'osm_rail_bay',
        'osm_gap_end',
        'staging_platform',
        'staging_barge',
        'pigeon_key_cottage_a',
        'pigeon_key_cottage_b',
        'pigeon_key_dock',
      ],
      xs: [-78, -60, -43, -31, -19, -7, 7, 25, 43, 55, 68],
      parts: ['body'],
      perVariant: { tris: 300, draws: 10 },
      tris: [90, 110, 120, 110, 40, 160, 300, 300, 180, 180, 90],
      height: [0, 10],
      heights: [
        [0.8, 0.9],
        [0.8, 0.9],
        [-0.5, 0],
        [-0.4, 0],
        [0.9, 1],
        [1.9, 2.1],
        [1.1, 1.2],
        [5.4, 5.8],
        [7.9, 8.1],
        [4.5, 4.7],
        [1.5, 1.7],
      ],
      sway: false,
      sharedMaterials: false,
      bays: {
        roots: [
          'nsm_bay',
          'nsm_bay_tall',
          'osm_arch_bay',
          'osm_girder_bay',
          'osm_rail_bay',
          'osm_gap_end',
          'staging_platform',
        ],
        lengthM: [41, 41, 18, 24, 24, 8, 10],
      },
    },
    atlas: {
      sheet: 'florida-keys',
      surfaces: [
        'pigeon_key_cottage_a_siding',
        'pigeon_key_cottage_a_trim',
        'pigeon_key_cottage_b_siding',
        'pigeon_key_cottage_b_trim',
        'pigeon_key_cottage_a_window_0',
        'pigeon_key_cottage_a_window_1',
        'pigeon_key_cottage_a_upper_windows',
        'pigeon_key_cottage_b_window_0',
        'pigeon_key_cottage_b_window_1',
      ],
    },
    textSurfaces: ['osm_gap_end_board'],
    convexParts: [],
    views: VARIANT_VIEWS,
  },
  {
    name: 'keys_tour_tram',
    script: 'props/keys_tour_tram.py',
    asset: 'models/traffic/keys-tour-tram',
    pack: 'base',
    region: 'florida-keys',
    kind: 'vehicle',
    budget: { tris: 900, draws: 7, materials: 7 },
    views: VIEWS,
  },
  {
    name: 'rental_convertible',
    script: 'props/rental_convertible.py',
    asset: 'models/traffic/rental-convertible',
    pack: 'base',
    region: 'florida-keys',
    kind: 'vehicle',
    budget: { tris: 380, draws: 7, materials: 7 },
    views: VIEWS,
  },
  {
    name: 'pickup_boat',
    script: 'props/pickup_boat.py',
    asset: 'models/traffic/pickup-boat',
    pack: 'base',
    region: 'florida-keys',
    kind: 'vehicle',
    budget: { tris: 700, draws: 7, materials: 7 },
    views: VIEWS,
  },
  {
    name: 'snowbird_rv',
    script: 'props/snowbird_rv.py',
    asset: 'models/traffic/snowbird-rv',
    pack: 'base',
    region: 'florida-keys',
    kind: 'vehicle',
    budget: { tris: 600, draws: 7, materials: 7 },
    views: VIEWS,
  },
  {
    name: 'keys_identity',
    script: 'props/keys_identity.py',
    asset: 'models/scenery/keys-identity',
    pack: 'base',
    region: 'florida-keys',
    kind: 'variants',
    budget: { materials: 13 },
    variants: {
      roots: [
        'key_deer_buck',
        'key_deer_doe',
        'keys_mile_marker',
        'keys_banyan',
        'keys_poinciana',
        'keys_frangipani',
        'duval_open_bar_a',
        'duval_open_bar_b',
        'keys_osprey_post',
      ],
      xs: [-42, -39, -36, -18, 4, 17, 31, 50, 65],
      parts: ['body'],
      perVariant: { tris: 480, draws: 8 },
      tris: [220, 200, 60, 320, 220, 160, 480, 420, 120],
      height: [0, 13],
      heights: [
        [1.3, 1.4],
        [0.65, 0.72],
        [1.59, 1.61],
        [11.8, 12.4],
        [6.8, 7.2],
        [4.6, 4.8],
        [7.99, 8.01],
        [5.49, 5.51],
        [7, 11],
      ],
      sway: false,
      sharedMaterials: false,
    },
    textSurfaces: ['keys_mile_marker_face', 'duval_open_bar_a_name', 'duval_open_bar_b_name'],
    convexParts: [],
    views: VARIANT_VIEWS,
  },
  {
    name: 'pedicab',
    script: 'props/pedicab.py',
    asset: 'models/traffic/pedicab',
    pack: 'base',
    region: 'florida-keys',
    kind: 'vehicle',
    budget: { tris: 380, draws: 7, materials: 7 },
    convexParts: [],
    views: VIEWS,
  },
];
