// The Pacific Northwest's own models (playtest 3, Codex batch CX4). Every row has
// `pack: 'region-pnw'` and `region: 'pacific-northwest'`, so its GLB lands in
// packs/region-pnw/assets/ and the per-region model budget counts it as the region's. CX4 appends
// here, after the two step-up bikes' rows (playtest 3, T10.2); no other batch edits this file.
import { VARIANT_VIEWS, VIEWS } from './views.mjs';

/** The nodes every bike export names, in the order the scripts make them. */
const BIKE_NODES = [
  'bike_body',
  'wheel_front',
  'wheel_rear',
  'fork',
  'seat_anchor',
  'bar_l',
  'bar_r',
  'peg_l',
  'peg_r',
  'light_head',
  'light_tail',
];

/** @type {import('../catalog.mjs').Prop[]} */
export const PNW_PROPS = [
  // The Grand Tourer 1100 and the Supersport 900 (playtest 3, T10.2, "Six bikes"): the region's two
  // step-up bikes, byte copies of the touring flagship and the Superbike under their own ids (the
  // rider-look rule draws `models/bikes/<bike id>`). Each row reuses its source bike's script, so a
  // rebuild writes the same bytes; Codex replaces the script with the bike's own later, under the
  // same name.
  {
    name: 'grand_tourer_1100',
    script: 'props/touring_flagship.py',
    asset: 'models/bikes/grand-tourer-1100',
    pack: 'region-pnw',
    region: 'pacific-northwest',
    kind: 'single',
    budget: { tris: 1500, draws: 7, materials: 7 },
    single: {
      root: 'bike',
      nodes: BIKE_NODES,
      size: [
        [0.5, 1.5],
        [0.6, 1.9],
        [1.2, 2.9],
      ],
    },
    views: VIEWS,
  },
  {
    name: 'supersport_900',
    script: 'props/superbike_1000.py',
    asset: 'models/bikes/supersport-900',
    pack: 'region-pnw',
    region: 'pacific-northwest',
    kind: 'single',
    budget: { tris: 1500, draws: 7, materials: 7 },
    single: {
      root: 'bike',
      nodes: BIKE_NODES,
      size: [
        [0.5, 1.4],
        [0.8, 1.8],
        [1.7, 2.7],
      ],
    },
    views: VIEWS,
  },
  {
    name: 'pdx_landmarks',
    script: 'props/pdx_landmarks.py',
    asset: 'models/landmarks/pdx-landmarks',
    pack: 'region-pnw',
    region: 'pacific-northwest',
    kind: 'variants',
    budget: { materials: 13 },
    variants: {
      roots: [
        'pdx_lift_tower_lod0',
        'pdx_lift_tower_lod1',
        'pdx_truss_bay',
        'pdx_lift_span',
        'pdx_bascule_pier',
        'pdx_st_johns_tower_lod0',
        'pdx_st_johns_tower_lod1',
        'pdx_roof_sign',
        'pdx_plaza',
        'pdx_chinatown_gate',
      ],
      xs: [-240, -190, -140, -90, -40, 10, 60, 110, 180, 250],
      parts: ['body'],
      perVariant: { tris: 800, draws: 10 },
      tris: [700, 100, 160, 260, 300, 800, 110, 400, 600, 500],
      height: [0, 125],
      heights: [
        [35.99, 36.01],
        [35.99, 36.01],
        [7.9, 8.1],
        [9.9, 10.1],
        [9.9, 10.1],
        [124.99, 125.01],
        [124.99, 125.01],
        [20, 22],
        [12.99, 13.01],
        [10.99, 11.01],
      ],
      sway: false,
      sharedMaterials: false,
      bays: { roots: ['pdx_truss_bay', 'pdx_lift_span'], lengthM: [40, 64] },
      lods: [
        { lod0: 'pdx_lift_tower_lod0', lod1: 'pdx_lift_tower_lod1' },
        { lod0: 'pdx_st_johns_tower_lod0', lod1: 'pdx_st_johns_tower_lod1' },
      ],
    },
    textSurfaces: ['pdx_roof_sign_words', 'pdx_chinatown_gate_plaque'],
    convexParts: [],
    views: VARIANT_VIEWS,
  },
  {
    name: 'pdx_downtown',
    script: 'props/pdx_downtown.py',
    asset: 'models/scenery/pdx-downtown',
    pack: 'region-pnw',
    region: 'pacific-northwest',
    kind: 'variants',
    budget: { materials: 10 },
    variants: {
      roots: [
        'pdx_cast_iron',
        'pdx_brick_loft',
        'pdx_office_block',
        'pdx_pink_tower_base',
        'pdx_pink_tower_mid',
        'pdx_pink_tower_crown',
        'pdx_food_cart_a',
        'pdx_food_cart_b',
        'pdx_food_cart_c',
        'pdx_bike_rack',
      ],
      xs: [-225, -175, -125, -75, -25, 25, 75, 125, 175, 225],
      parts: ['body'],
      perVariant: { tris: 300, draws: 14 },
      tris: [300, 220, 200, 60, 40, 90, 160, 160, 160, 40],
      height: [0, 28],
      heights: [
        [11.99, 12.01],
        [24.99, 25.01],
        [27.99, 28.01],
        [6.99, 7.01],
        [13.99, 14.01],
        [7.99, 8.01],
        [2.99, 3.01],
        [2.99, 3.01],
        [2.99, 3.01],
        [1.59, 1.61],
      ],
      sway: false,
      sharedMaterials: false,
    },
    atlas: {
      sheet: 'pacific-northwest',
      surfaces: [
        ...['pdx_cast_iron', 'pdx_brick_loft', 'pdx_office_block'].flatMap((n) =>
          Array.from({ length: 4 }, (_, i) => `${n}_facade_${i}`),
        ),
        ...['base', 'mid', 'crown'].flatMap((m) =>
          Array.from({ length: 8 }, (_, i) => `pdx_pink_tower_${m}_facade_${i}`),
        ),
        ...['a', 'b', 'c'].map((s) => `pdx_food_cart_${s}_front`),
      ],
    },
    textSurfaces: ['pdx_food_cart_a_name', 'pdx_food_cart_b_name', 'pdx_food_cart_c_name'],
    convexParts: [],
    views: VARIANT_VIEWS,
  },
  .../** @type {[string,string,number,number][]} */ ([
    ['pdx_streetcar', 'pdx-streetcar', 700, 7],
    ['wagon_with_kayaks', 'wagon-with-kayaks', 380, 7],
    ['camper_van', 'camper-van', 450, 8],
    ['log_truck', 'log-truck', 800, 8],
  ]).map(([name, id, tris, materials]) => ({
    name,
    script: `props/${name}.py`,
    asset: `models/traffic/${id}`,
    pack: 'region-pnw',
    region: 'pacific-northwest',
    kind: /** @type {const} */ ('vehicle'),
    budget: { tris, draws: materials, materials },
    views: VIEWS,
  })),
  {
    name: 'gorge_landmarks',
    script: 'props/gorge_landmarks.py',
    asset: 'models/landmarks/gorge-landmarks',
    pack: 'region-pnw',
    region: 'pacific-northwest',
    kind: 'variants',
    budget: { materials: 11 },
    variants: {
      roots: [
        'vista_house_lod0',
        'vista_house_lod1',
        'multnomah_falls_lod0',
        'multnomah_falls_lod1',
        'multnomah_lodge',
        'gorge_arch_bay',
        'gorge_arch_span_46',
      ],
      xs: [-220, -185, -120, -45, 20, 65, 100],
      parts: ['body'],
      perVariant: { tris: 900, draws: 8 },
      tris: [700, 210, 900, 270, 600, 560, 880],
      height: [0, 190],
      heights: [
        [16.99, 17.01],
        [16.99, 17.01],
        [189.99, 190.01],
        [189.99, 190.01],
        [14.99, 15.01],
        [-0.11, -0.09],
        [-0.11, -0.09],
      ],
      sway: false,
      sharedMaterials: false,
      bays: { roots: ['gorge_arch_bay', 'gorge_arch_span_46'], lengthM: [24, 46] },
      lods: [
        { lod0: 'vista_house_lod0', lod1: 'vista_house_lod1' },
        { lod0: 'multnomah_falls_lod0', lod1: 'multnomah_falls_lod1' },
      ],
    },
    convexParts: [],
    views: VARIANT_VIEWS,
  },
  {
    name: 'pnw_identity',
    script: 'props/pnw_identity.py',
    asset: 'models/scenery/pnw-identity',
    pack: 'region-pnw',
    region: 'pacific-northwest',
    kind: 'variants',
    budget: { materials: 4 },
    variants: {
      roots: ['pnw_madrone_a', 'pnw_madrone_b', 'gorge_guard_wall'],
      xs: [-18, 0, 18],
      parts: ['body'],
      perVariant: { tris: 220, draws: 8 },
      tris: [220, 180, 120],
      height: [0, 11],
      heights: [
        [8, 11],
        [5.5, 7],
        [0.9, 0.91],
      ],
      sway: false,
      sharedMaterials: false,
    },
    convexParts: [],
    views: VARIANT_VIEWS,
  },
];
