"""The Keys data probe: what the one US 1 extract actually holds, written up as markdown.

Every number in the report is computed here from the cached extract, so a re-run on a newer
extract rewrites it honestly.
"""

from __future__ import annotations

from collections import Counter

import numpy as np

from tbgis.fetch import FetchMeta
from tbgis.graph import Graph
from tbgis.osm import Way, polyline_length_m
from tbgis.stretch import gaussian
from tbgis.tmerc import Frame

# The southbound carriageway's first node at the top of the Keys extract, and Key West.
TOP = (25.2308242, -80.4323259)
KEY_WEST = (24.5601895, -81.781867)


def _share(ways: list[Way], key: str, total: float) -> str:
    c: Counter[str] = Counter()  # metres per tag value
    for w in ways:
        c[w.tags.get(key, "(none)")] += round(polyline_length_m(w.coords))
    return ", ".join(f"`{k}` {100 * v / total:.1f}%" for k, v in c.most_common(6))


def report(ways: list[Way], meta: FetchMeta, frame: Frame) -> str:
    total = sum(polyline_length_m(w.coords) for w in ways)
    nodes = sum(len(w.coords) for w in ways)
    bridges = sorted((w for w in ways if w.is_bridge), key=lambda w: -polyline_length_m(w.coords))
    steps = Graph(ways).path(TOP, KEY_WEST)
    pts = [steps[0].a, *(s.b for s in steps)]
    xz = np.array([frame.to_world(*p) for p in pts])
    seg = np.hypot(np.diff(xz[:, 0]), np.diff(xz[:, 1]))
    cum = np.concatenate([[0.0], np.cumsum(seg)])
    path_len = float(cum[-1])
    grid = np.arange(0, path_len, 1.0)
    idx = np.clip(np.searchsorted(cum, grid, side="right") - 1, 0, len(seg) - 1)
    heading = np.unwrap(np.arctan2(np.diff(xz[:, 0]), -np.diff(xz[:, 1])))[idx]
    kappa = np.abs(np.gradient(gaussian(heading, 35.0), 1.0))
    bridge_on_path = sum(s.length_m for s in steps if s.way.is_bridge)
    long_bridge_nodes = [len(w.coords) for w in bridges if polyline_length_m(w.coords) >= 1000]
    lines = [
        "# Keys data probe: US 1 in OpenStreetMap",
        "",
        "Generated by `tbgis probe` from one Overpass query; every number below is computed from the",
        "cached extract, not typed by hand. Road data © OpenStreetMap contributors (ODbL 1.0).",
        "",
        "## The query",
        "",
        "```",
        meta.query,
        "```",
        "",
        f"Retrieved {meta.retrievedAt} from `{meta.url}`: {meta.bytes:,} bytes, SHA-256 `{meta.sha256}`.",
        "",
        "## What it holds",
        "",
        f"- {len(ways)} ways, {nodes:,} geometry nodes, {total / 1000:.1f} km of way length (both",
        "  carriageways counted where the road is divided).",
        f"- Mean node spacing {total / max(1, nodes - len(ways)):.0f} m. "
        "Long bridges are drawn as a few straight",
        f"  segments: the {len(long_bridge_nodes)} bridge ways over 1 km have {long_bridge_nodes} nodes.",
        f"- `highway`: {_share(ways, 'highway', total)}.",
        f"- `lanes`: {_share(ways, 'lanes', total)}.",
        f"- `oneway`: {_share(ways, 'oneway', total)} (the road is divided in places).",
        f"- `maxspeed`: {_share(ways, 'maxspeed', total)}.",
        f"- `bridge`: {_share(ways, 'bridge', total)}; `layer`: {_share(ways, 'layer', total)}.",
        f"- `surface`: {_share(ways, 'surface', total)}. No way has a `shoulder` tag"
        if not any("shoulder" in w.tags for w in ways)
        else f"- `surface`: {_share(ways, 'surface', total)}.",
        "- No elevation: OSM carries none, and bridge ways have no deck height.",
        "",
        "## The drivable path",
        "",
        f"- The southbound path from the top of the extract to Key West is {path_len / 1000:.1f} km, "
        f"{len(steps)} segments, one connected graph.",
        f"- {bridge_on_path / 1000:.1f} km of it ({100 * bridge_on_path / path_len:.0f}%) is on bridges.",
        f"- After a 35 m heading smoothing: {100 * float(np.mean(kappa < 1 / 2000)):.0f}% of the path "
        f"has a radius over 2 km (effectively straight), {100 * float(np.mean(kappa > 1 / 500)):.1f}% "
        f"is tighter than 500 m, and the tightest bend is {1 / float(kappa.max()):.0f} m.",
        "",
        "## Longest bridge ways",
        "",
        "| Way | Length | Name tag | Lanes | One-way | Nodes |",
        "|---|---|---|---|---|---|",
    ]
    for w in bridges[:10]:
        lines.append(
            f"| {w.id} | {polyline_length_m(w.coords):,.0f} m | {w.tags.get('name', '')} | "
            f"{w.tags.get('lanes', '')} | {w.tags.get('oneway', 'no')} | {len(w.coords)} |"
        )
    lines += [
        "",
        "## Verdict",
        "",
        "- Usable. US 1 is continuous, consistently tagged (`ref`, `maxspeed`, `bridge`, `lanes`),",
        "  and the travel path through the divided stretches can be found automatically.",
        "- Mostly straight and flat, as the roadmap suspected. Bends are gentle and bridges are",
        "  straight lines, so fun has to come from bridge humps, traffic and the pace of the islands.",
        "- Elevation needs two sources: USGS 3DEP for the land, and synthesized decks and humps for",
        "  every bridge, since 3DEP is bare earth (it reads the water under a bridge) and OSM has no",
        "  heights at all. The bake's summary prints the land range it found on its stretch.",
        "",
        f"The frame is transverse Mercator at {frame.origin_lat_deg}, {frame.origin_lon_deg}"
        " (the region's frame, shared with the hand-made network).",
        "",
    ]
    return "\n".join(lines)
